### ISSUE TITLE
client.full_upload() return bytearray size 65536

### ISSUE THREAD

**Issue by Lamelynx** [gijzelaerr/python-snap7#127] opened 2019-08-29 07:45 UTC
Shouldn't client.full_upload() return the actual FC's bytearray size?
In my code i do it manually with:
```
result =  client.full_upload('FC', 1000)
client.download(result[0][:result[1]])
```
If i download full result[0] bytearray i got size error.
Tested on S7-400 ans PLCsim

**Comment by Lamelynx** [comment] 2019-08-29 07:47
Just for clarification:
client.full_upload() return the actual size as result[1] but len(result[0]) returns 65536

**Comment by spreeker** [comment] 2019-09-03 12:14
Hai!  This could very well be the case.  Could you create a pull request with a test showing your solution?

Many function have never been used by me in production so still could contain mistakes or do not handle some edge conditions well. It could also be simple snap7 libary behaviour in which case we cannot do something about it here.

**Comment by nikteliy** [comment] 2020-12-02 11:43
I have tried to reproduce bug on my ET200S. No luck. Is it still a thing?
![full_upload_test](https://user-images.githubusercontent.com/52915342/100868346-2a117480-34a4-11eb-822a-a3047e6fda5f.PNG)

**Comment by swamper123** [comment] 2020-12-02 11:56
Since 2019 some changes have been made, which may have fixed it. (see #158 )
I am not able to verify that one, sorry. :/

**Comment by gijzelaerr** [comment] 2020-12-02 12:12
ah yes, forgot to close this issue I realise now.

**Closed by gijzelaerr** 2020-12-02 12:12 UTC
Labels: bug
