### ISSUE TITLE
Windows test runs fail

### ISSUE THREAD

**Issue by swamper123** [gijzelaerr/python-snap7#206] opened 2020-10-30 13:34 UTC
Tested different ways in #205 to run tests on the windows build here in github actions.

I found out:
- the error is not depending on a special file (see [here](https://github.com/gijzelaerr/python-snap7/pull/205/commits/9e7e12fbf1605ee3c9f86e70e674668a6405e7e1), where just test_client was running, which always passed in all tests! It seems to be the end of the test and perhaps if an error/fault. 
![grafik](https://user-images.githubusercontent.com/24408657/97708241-be10aa80-1ab8-11eb-80b8-5a1e00fb251d.png)
- normal failed python tests seemed to be fine. They are marked as F normally. I guess there is something behind the python curtain crashing and causing trouble. 
[If test_partner was not tested:](https://github.com/gijzelaerr/python-snap7/runs/1332069347)
![grafik](https://user-images.githubusercontent.com/24408657/97709810-34aea780-1abb-11eb-996b-019e2f58bcd1.png)
So I guess there may be one source of trouble. I saw that you, @gijzelaerr, added something with sudo in the MakeFile, does this may be a reason or does that not influence the windows built?
- the python version doesn't matter (since once 3.7 ran, once python3.9), but should be fixed on a special version (3.8 or 3.9 for the start).
- choco may install the newest version of python (3.9.0.), but pytest ran with Python 3.7.9. It should run with the same version to be correct (in case more python versions shall be tested on windows 😨 )

So my suspect is:
- pytest and windows hate eachother and crashes in the end (independent of the result)
- something is crashing behind the curtain and is then crashing pytest. Perhaps the testservers? Perhaps missing admin rights for something?

**Comment by gijzelaerr** [comment] 2020-11-02 14:05
duplicate of https://github.com/gijzelaerr/python-snap7/issues/203

**Closed by gijzelaerr** 2020-11-02 14:05 UTC
