### ISSUE TITLE
version 1.4 broken on python 3.8

### ISSUE THREAD

**Issue by haronaut** [gijzelaerr/python-snap7#517] opened 2024-05-14 12:04 UTC
Tested on python 3.8.10

If I run `import snap7` I get the following error:

`site-packages/snap7/server/__init__.py", line 77, in Server
    def register_area(self, area_code: int, index: int, userdata: ctypes.Array[ctypes.c_int8]):
TypeError: '_ctypes.PyCArrayType' object is not subscriptable`

python-snap7 version 1.3 does not have this issue.

**Comment by gijzelaerr** [comment] 2024-05-14 13:13
duplicate of https://github.com/gijzelaerr/python-snap7/issues/511

i think i should retract 1.4 since that release  was incorrectly tagged as supporting python 3.7

**Closed by gijzelaerr** 2024-05-14 13:13 UTC

**Comment by gijzelaerr** [comment] 2024-05-14 13:19
`1.4` has been "yanked". `Python > 3.8` should now resolve to `python-snap7=>1.4.1`, `python=<3.8` to `python-snap7<1.4`
